import { Inter } from "next/font/google";
import "@/app/globals.css";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black`}>
        <main className="h-screen w-full grid grid-cols-1 md:grid-cols-2 lg:grid-cols-[1fr_600px] gap-4">
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
