import { Inter } from "next/font/google";
import "@/app/globals.css";
import Navbar from "@/components/global/Navbar";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col`}>
        <Navbar />
        <main className="container">{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
