import { Inter } from "next/font/google";
import "@/app/globals.css";
import Navbar from "@/components/global/Navbar";
import { Toaster } from "react-hot-toast";
import Sidebar from "@/components/global/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-col pt-[8vh] bg-slate-100`}
      >
        <Navbar />
        <div className="md:pl-[250px]">
          <Sidebar />
          <main className="p-4">{children}</main>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
